# AWS credentials
AWS_ACCESS_KEY_ID = 'AKIAIOSFODNN7EXAMPLE'
AWS_SECRET_ACCESS_KEY = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
AWS_SESSION_TOKEN = 'FwoGZXIvYXdzEBYaDJKLmnopqrsTUvwxYiK3Abc'
AWS_REGION = 'us-east-1'

S3_BUCKET = 'my-secret-bucket'
S3_ACCESS_KEY = 'AKIAI44QH8DHBEXAMPLE'
S3_SECRET_KEY = 'je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY'
